### ISSUE TITLE
VDF panics on invalid input

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1165]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotInField("0xc1be53e60fa9bb19bace633894a64b542c91f9eac22368df7914ac6e83ad3c00")', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/de7c4e42314c56528640e3b663aa10e0caa6bd9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/de7c4e42314c56528640e3b663aa10e0caa6bd9b/src/libcore/result.rs:800
  12: stegos_crypto::vdf::unchecked_bytes_to_fv
             at crypto/src/vdf/mod.rs:57
  13: stegos_crypto::vdf::VDF::verify
             at crypto/src/vdf/mod.rs:144
  14: stegos_blockchain::validation::<impl stegos_blockchain::blockchain::Blockchain>::validate_micro_block
             at blockchain/src/validation.rs:1048
  15: stegos_blockchain::blockchain::Blockchain::recover_block
             at blockchain/src/blockchain.rs:355
  16: stegos_blockchain::blockchain::Blockchain::recover
             at blockchain/src/blockchain.rs:328
  17: stegos_blockchain::blockchain::Blockchain::new
             at blockchain/src/blockchain.rs:284
  18: stegosd::run
```

**Comment by rtsisyk** [comment]
Fixed
