### ISSUE TITLE
Valueshuffle panic on incorrect tx processing

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#1499]
' panicked at 'assertion failed: `(left == right)`
  left: `H(379977982f66e434344ebee4ee669c3b097f03c26d5ff560934651cf8d917e76)`,
 right: `H(6c930647d7c3d4cf005396c333948f9f89d61c9ddc11175141980dff33b60219)`', wallet/src/storage.rs:299:21
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  13: stegos_wallet::storage::AccountDatabase::prune_txs
             at wallet/src/storage.rs:0
  14: <stegos_wallet::UnsealedAccountService as futures::future::Future>::poll
             at wallet/src/lib.rs:1529
  15: <stegos_wallet::AccountService as futures::future::Future>::poll
             at wallet/src/lib.rs:1822
  16: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  17: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  18: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  19: futures::task_impl::std::set
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
  20: futures::task_impl::Spawn<T>::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  21: futures::task_impl::Spawn<T>::poll_fn_notify
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
  22: futures::task_impl::Spawn<T>::poll_future_notify
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  23: tokio_threadpool::task::Task::run::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/task/mod.rs:145
  24: core::ops::function::FnOnce::call_once
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libcore/ops/function.rs:223
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/panic.rs:316
  26: std::panicking::try::do_call
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/panicking.rs:287
  27: __rust_maybe_catch_panic
             at src/libpanic_abort/lib.rs:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by vldm** [comment]
Closed, because we removing all snowball/valueshuffle parts in latest dev
