### ISSUE TITLE
Better handling of EADDRINUSE

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#438]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(Other(A(Transport(A(Underlying(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))))))', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/macros.rs:26
   9: stegos_network::libp2p_network::new_service
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/result.rs:808
             at network/src/libp2p_network/mod.rs:161
  10: stegos_network::libp2p_network::Libp2pNetwork::new
             at network/src/libp2p_network/mod.rs:65
  11: stegos::main
             at src/stegos.rs:133
             at src/stegos.rs:172
  12: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
```

Stack trace should be printed only in case of crash/internal error. EADDRINUSE is regular case.

**Comment by rtsisyk** [comment]
Set bind_port = 0 for default as a temporary workaround.
